### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 331319341** [b3b/able#1]
requirements = hostpython2,kivy,android,able       able  does not exist ？？

**Comment by 331319341** [comment]
can not pip install able    ,requirements = hostpython2,kivy,android,able      Must fail！Seeking solution

**Comment by b3b** [comment]
This package can only be used with Buildozer packager, not with pip.

To build application with `able`, buildozer should be installed first:
https://github.com/kivy/buildozer/blob/master/docs/source/installation.rst

After the buildozer is installed, you can build the sample application as follows:
 ```
cd able/examples/alert
buildozer android_new debug
```

To build any other application, path to `able` recipe should be set in the `buildozer.spec` of the application.  Something, like:
`p4a.local_recipes = /home/user/src/able/recipes`

Does it helps, or maybe more detailed description is needed?

**Comment by 331319341** [comment]
thank you very much! Has been installed successfully! You helped me! There are problems and then ask, thank you
