### ISSUE TITLE
Add connect by mac address or through java class bluetoothdevice

### ISSUE THREAD

**Issue by dgatf** [b3b/able#14]
This is not an issue but a request

Please add a function to connect to a device by the mac address or though the java class _bluetoothdevice_ that can be obtained from the paired devices list: `autoclass('android.bluetooth.BluetoothAdapter').getDefaultAdapter().getBondedDevices().toArray()`

Use case: not always is desired to scan devices, but quickly connect through the mac address or java class _bluetoothdevice_ from paired devices list

Thanks

**Comment by b3b** [comment]
Thanks for interesting ideas. Indeed,sometimes scanning is redundant.
I'll see what could be done.

**Comment by b3b** [comment]
Currently, it is possible to use library to get a list of paired devices, and to connect to device by a MAC address.
Usage example: https://herethere.me/pythonhere/examples/ble.html#get-list-of-paired-ble-devices
