### ISSUE TITLE
send data to bt device

### ISSUE THREAD

**Issue by PapoKarlo** [b3b/able#16]
how to receive data from device after connect by mac address?
on_characteristic_read()
show nothing after read_characteristic(characteristic) in loop

**Comment by PapoKarlo** [comment]
i found solution, thru notofications
thanx for your interface, it works :)

**Comment by b3b** [comment]
@PapoKarlo I've been in offline mode for a while, glad you found a solution :)
Yes, the way of accessing the data (reading, listening) depends on the properties of the characteristic.
