### ISSUE TITLE
Change recipe name to avoid name clash

### ISSUE THREAD

**Issue by b3b** [b3b/able#19]
Currently, in case `able` recipe was not found during the build, python-for-android install non-related library from PyPi.
Related issues: #3 #4 #18

**Comment by b3b** [comment]
Installation method is changed. Instead of messing with local recipes, now it is possible to just use package from PyPi: https://pypi.org/project/able-recipe/

**Comment by Enkumicahel** [comment]
Awesome @b3b better this ways I hope
