### ISSUE TITLE
After upgrading to new recipe, scanning doesn't work.

### ISSUE THREAD

**Issue by dwmoffatt** [b3b/able#20]
After upgrading to use the new recipe, scanning has stopped working. 

I get this error message: 

11-14 07:22:28.012  2773  4619 E BluetoothUtils: Permission denial: Need ACCESS_FINE_LOCATION permission to get scan results

**Comment by dwmoffatt** [comment]
couple more pieces of information below is the configuration that works and doesn't work.

Works - config in buildozer
android.api = 28
android.minapi = 21

Not working - config in buildozer
android.api = 30
android.minapi = 22

**Comment by b3b** [comment]
@dwmoffatt Thanks for details. I have not tried to build with new SDKs yet.

ACCESS_FINE_LOCATION permission is required for SDK >= 29, according to https://developer.android.com/about/versions/10/privacy/changes

I updated the recipe, and also `ACCESS_FINE_LOCATION` should be added to the app buildozer.spec
```
android.permissions = BLUETOOTH, BLUETOOTH_ADMIN, ACCESS_FINE_LOCATION
```

**Comment by dwmoffatt** [comment]
I'll try it out tonight!
