### ISSUE TITLE
Error on last release

### ISSUE THREAD

**Issue by PapoKarlo** [b3b/able#23]
Hi , i get error on last release, on 1.0.3 all is ok. What can be wrong?

BLE-python: Connected to GATT server, status:0
BLE-python: onServicesDiscovered - success
python  :  Traceback (most recent call last):
python  :    File "jnius/jnius_proxy.pxi", line 50, in jnius.jnius.PythonJavaClass.invoke
python  :    File "jnius/jnius_proxy.pxi", line 76, in jnius.jnius.PythonJavaClass._invoke
python  :    File "/var/ttgo/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ttgobt/able/android/jni.py", line 54, in on_services
python  :    File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
python  :    File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
python  :    File "/var/ttgo/.buildozer/android/app/main.py", line 183, in on_services
python  :    File "/var/ttgo/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ttgobt/able/android/dispatcher.py", line 74, in enable_notifications
python  :    File "/var/ttgo/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ttgobt/able/queue.py", line 18, in wrapper
python  :    File "/var/ttgo/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ttgobt/able/queue.py", line 63, in enque
python  :    File "/var/ttgo/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ttgobt/able/queue.py", line 36, in wrapped
python  :    File "/var/ttgo/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ttgobt/able/queue.py", line 77, in execute_next
python  :    File "/var/ttgo/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ttgobt/able/queue.py", line 90, in execute_task
python  :    File "/var/ttgo/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ttgobt/able/dispatcher.py", line 140, in write_descriptor
python  :    File "jnius/jnius_export_class.pxi", line 763, in jnius.jnius.JavaMethod.__call__
python  :    File "jnius/jnius_conversion.pxi", line 130, in jnius.jnius.populate_args
python  :    File "jnius/jnius_conversion.pxi", line 586, in jnius.jnius.convert_pyarray_to_java
python  :  TypeError: an integer is required

**Comment by b3b** [comment]
Hi, @PapoKarlo.
Thanks for details, last changes in `force_convertible_to_java_array` utility broke the `BluetoothDispatcher.enable_notifications`.

**Comment by b3b** [comment]
Fixed in 1.0.6 ,
error was caused by a broken conversion of the `BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE` .

**Comment by PapoKarlo** [comment]
thank you! :)
