### ISSUE TITLE
ImportError: cannot import name BluetoothDispatcher

### ISSUE THREAD

**Issue by slinger360** [b3b/able#4]
'''File "bleandroid.py", line 7, in <module>
04-14 19:48:16.062  8847  9321 I python  :  ImportError: cannot import name BluetoothDispatcher
04-14 19:48:16.062  8847  9321 I python  : Python for android ended.'''

Does your library even work?

**Comment by b3b** [comment]
Can't reproduce, there is no `bleandroid.py` module in the project. Please report if it is still not working.
Thanks!

**Comment by Enkumicahel** [comment]
@FalkorDev were you able to fix this issue? I am stuck.
