### ISSUE TITLE
Is Python3 support in road map?

### ISSUE THREAD

**Issue by jacklinquan** [b3b/able#6]
Kivy is dropping Python2 very soon. 
Is there any plan for Python3 support?

**Comment by b3b** [comment]
Thank you for raising this, I missed this change.
Yes, Python 3 support will be added soon.

- https://github.com/kivy/kivy/issues/6253
- https://github.com/kivy/python-for-android/pull/1918

**Comment by jacklinquan** [comment]
Thank you a lot!
"able" is a very useful python package for android application.
It's very exciting to have the python 3 version of it.

**Comment by b3b** [comment]
Python 3 compatibility is added.
