### ISSUE TITLE
Preparing a development environment

### ISSUE THREAD

**Issue by juasiepo** [b3b/able#8]
I have the testapp running in my mobile phone and it can connect to the server.go successfully

Now I am preparing a development environment. While trying to launch the testapp on my linux box I get the main window successfully but when I click on connect button I get the following error:
"
   File "/home/juan/git/able/.venv/lib/python3.7/site-packages/able/dispatcher.py", line 14, in __getattr__
     raise Exception(self.msg)
 Exception: BLE is not implemented for platform
"
It makes sense as the BLE is expected to work with the Android Bluetooth Low Energy API.

The other option I am implementing to create a development environment is to install the [kivy-remote-shell](https://github.com/kivy/kivy-remote-shell)  on my android phone so I will get a python with all the libraries that will allow me to run quick tests. But for the moment I am having some issues installing it.

Any Idea about how to create a development environment?

Thanks for your time

**Comment by b3b** [comment]
I plan to add something like a Kivy Launcher with BLE support, but can't recommend any convenient option so far.

One more option I use is granting storage permission to application, and running scripts from SDCard, like
```python
import sys
sys.path.append('/storage/sdcard1/scripts')
import myscript
```

**Comment by juasiepo** [comment]
I don't get your point with the import approach.

Do I need a python3 interpreter installed on my android phone?
Can you elaborate a little bit more?

Thanks for your time

**Comment by b3b** [comment]
Yes, I meant running the testapp on Android device.
And importing modules with test cases located in the SDCard from this app.
